"""add unique constraint on gymnast_scores

Revision ID: b216ac9053ad
Revises: 7ca9d363ca7f
Create Date: 2019-06-14 08:32:20.359381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b216ac9053ad'
down_revision = '7ca9d363ca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gym_score_ux1', 'gymnast_scores', ['gymnast_id', 'apparatus_id'])
    op.drop_constraint('scores_ux1', 'gymnast_scores', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scores_ux1', 'gymnast_scores', ['gymnast_id', 'apparatus_id'])
    op.drop_constraint('gym_score_ux1', 'gymnast_scores', type_='unique')
    # ### end Alembic commands ###
